version: '2' 
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    env_file:
      - ./hadoop.env
  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./hadoop.env
  spark-notebook:
    build:
      context: "./spark-notebook"
      dockerfile: "Dockerfile"
    container_name: spark-notebook
    environment:
      - SPARK_EXECUTOR_MEMORY=1G
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
  hue:
    image: bde2020/hdfs-filebrowser:3.11
    environment:
      - NAMENODE_HOST=namenode
  datascience-notebook:
    image: gottit/jupyter-py27:1.0
    container_name: datascience-notebook
    env_file:
      - ./hadoop.env
    volumes:
    - ./data/jupyter:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark-master:7077
