version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    ports:
    - "6066:6066"
    - "8080:8080"
    - "7077:7077"
    - "4040:4040"
    networks:
      - workbench
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8080
    env_file:
      - ./hadoop.env

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    ports:
    - "8081:8081"
    networks:
      - workbench
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8081
    env_file:
      - ./hadoop.env

networks:
  workbench:
    external: true
